[package]
name = "karte-codegen"
version.workspace = true
edition.workspace = true
authors.workspace = true
description.workspace = true
license.workspace = true

[lints]
workspace = true

[dependencies]
karte-hir = { path = "../karte-hir" }
karte-diagnostics = { path = "../karte-diagnostics" }
karte-lir = { path = "../karte-lir" }
karte-mir = { path = "../karte-mir" }
karte-common = { path = "../karte-common" }
