[package]
name = "karte-codegen"
version.workspace = true
edition.workspace = true
authors.workspace = true
description.workspace = true
license.workspace = true

[lints]
workspace = true

[dependencies]
karte-hir = { path = "../karte-hir" }
karte-diagnostics = { path = "../karte-diagnostics" }
karte-lir = { path = "../karte-lir" }
karte-mir = { path = "../karte-mir" }
karte-common = { path = "../karte-common" }
karte-lexer = { path = "../karte-lexer" }
karte-parser = { path = "../karte-parser" }
log.workspace = true

# Windows系统API
windows-sys = { version = "0.48", features = ["Win32_System_Memory", "Win32_Foundation"] }

# Unix系统支持
libc = "0.2"
tempfile = "3.2"

[dev-dependencies]
env_logger = "0.10"
