[package]
name = "karte-module-system"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[lints]
workspace = true

[dependencies]
indicatif = "0.17"
karte-diagnostics = { path = "../karte-diagnostics" }
karte-escape-analysis = { path = "../karte-escape-analysis" }
karte-hir = { path = "../karte-hir" }
karte-ir-codec = { path = "../karte-ir-codec" }
karte-lir = { path = "../karte-lir" }
karte-lexer = { path = "../karte-lexer" }
karte-mir = { path = "../karte-mir" }
karte-parser = { path = "../karte-parser" }
log.workspace = true
rayon = "1"
serde.workspace = true
serde_json.workspace = true
toml = "0.8"
