[package]
name = "karte-cli"
version.workspace = true
edition.workspace = true
authors.workspace = true
description = "Command-line interface for Karte compiler"
license.workspace = true

[lints]
workspace = true

[[bin]]
name = "karte"
path = "src/main.rs"

[dependencies]
karte-lexer = { path = "../karte-lexer" }
karte-parser = { path = "../karte-parser" }
karte-diagnostics = { path = "../karte-diagnostics" }
karte-codegen = { path = "../karte-codegen" }
karte-mir = { path = "../karte-mir" }
karte-hir = { path = "../karte-hir" }
karte-lir = { path = "../karte-lir" }
env_logger.workspace = true
log.workspace = true
clap = { version = "4.4", features = ["derive"] }
karte-ir-codec = { path = "../karte-ir-codec" }
serde.workspace = true
karte-rt = { path = "../karte-rt" }
rayon = "1.11.0"
serde_json = "1.0"
karte-module-system = { path = "../karte-module-system" }

