[package]
name = "karte-diagnostics"
version.workspace = true
edition.workspace = true
authors.workspace = true
description = "Diagnostic system for Karte compiler"
license.workspace = true

[lints]
workspace = true

[dependencies]
thiserror.workspace = true
serde.workspace = true
miette.workspace = true
log.workspace = true
karte-ir-codec = { path = "../karte-ir-codec" }
karte-ir-derive = { path = "../karte-ir-derive" }
nom.workspace = true

[lib]