[package]
name = "karte-common"
version.workspace = true
edition.workspace = true
authors.workspace = true
description.workspace = true
license.workspace = true

[lints]
workspace = true

[dependencies]
karte-ir-codec = { path = "../karte-ir-codec" }
karte-ir-derive = { path = "../karte-ir-derive" }
nom.workspace = true
serde_json.workspace = true
