[package]
name = "karte-lir"
version.workspace = true
edition.workspace = true
authors.workspace = true
description.workspace = true
license.workspace = true

[lints]
workspace = true

[dependencies]
karte-diagnostics = { path = "../karte-diagnostics" }
karte-mir = { path = "../karte-mir" }
karte-hir = { path = "../karte-hir" }
karte-common = { path = "../karte-common" }
karte-ir-codec = { path = "../karte-ir-codec" }
karte-ir-derive = { path = "../karte-ir-derive" }
log.workspace = true
nom.workspace = true
once_cell.workspace = true
