[package]
name = "karte-lir"
version.workspace = true
edition.workspace = true
authors.workspace = true
description.workspace = true
license.workspace = true

[dependencies]
karte-diagnostics = { path = "../karte-diagnostics" }
karte-mir = { path = "../karte-mir" }
karte-hir = { path = "../karte-hir" }
