[[modules]]
id = "std.core"
path = "core.karte"

[[modules]]
id = "std.math"
path = "math.karte"

[[modules]]
id = "std.list"
path = "list.karte"

[[modules]]
id = "std.algorithm"
path = "algorithm.karte"

[[modules]]
id = "std.euler"
path = "euler.karte"

[[modules]]
id = "std.string"
path = "string.karte"

[[modules]]
id = "std.io"
path = "io.karte"

[[modules]]
id = "std.hashmap"
path = "hashmap.karte"

[[modules]]
id = "std.result"
path = "result.karte"

[[modules]]
id = "std.prelude"
path = "prelude.karte"
deps = ["std.core", "std.math", "std.string", "std.io"]
